"""3D分子结构服务 - SMILES转3D坐标"""
import os
import tempfile
from typing import Optional, Dict
from rdkit import Chem
from .utils import validate_smiles, _get_allchem


def smiles_to_sdf(smiles: str, add_hydrogens: bool = True) -> Optional[str]:
    """将SMILES转换为SDF格式字符串（含3D坐标）"""
    mol = validate_smiles(smiles)
    if mol is None:
        return None
    
    AllChem = _get_allchem()
    if AllChem is None:
        return None
    
    try:
        if add_hydrogens:
            mol = Chem.AddHs(mol)
        
        # 生成3D构象
        params = AllChem.ETKDGv3()
        params.randomSeed = 42
        ret = AllChem.EmbedMolecule(mol, params)
        if ret == -1:
            # ETKDGv3失败，回退到基础Embed
            ret = AllChem.EmbedMolecule(mol, randomSeed=42)
        
        if ret == -1:
            return None
        
        # MMFF力场优化
        AllChem.MMFFOptimizeMolecule(mol, mmffVariant='MMFF94')
        
        # 返回SDF字符串
        return Chem.MolToMolBlock(mol, includeStereo=True)
    except Exception:
        return None


def smiles_to_pdb(smiles: str, add_hydrogens: bool = True) -> Optional[str]:
    """将SMILES转换为PDB格式字符串"""
    mol = validate_smiles(smiles)
    if mol is None:
        return None
    
    AllChem = _get_allchem()
    if AllChem is None:
        return None
    
    try:
        if add_hydrogens:
            mol = Chem.AddHs(mol)
        
        params = AllChem.ETKDGv3()
        params.randomSeed = 42
        ret = AllChem.EmbedMolecule(mol, params)
        if ret == -1:
            ret = AllChem.EmbedMolecule(mol, randomSeed=42)
        if ret == -1:
            return None
        
        AllChem.MMFFOptimizeMolecule(mol, mmffVariant='MMFF94')
        
        # 写入临时PDB
        with tempfile.NamedTemporaryFile(suffix='.pdb', delete=False, mode='w') as f:
            tmp_path = f.name
        
        Chem.MolToPDBFile(mol, tmp_path)
        with open(tmp_path, 'r') as f:
            pdb = f.read()
        os.unlink(tmp_path)
        return pdb
    except Exception:
        return None


def smiles_to_xyz(smiles: str, add_hydrogens: bool = True) -> Optional[str]:
    """将SMILES转换为XYZ格式字符串"""
    mol = validate_smiles(smiles)
    if mol is None:
        return None
    
    AllChem = _get_allchem()
    if AllChem is None:
        return None
    
    try:
        if add_hydrogens:
            mol = Chem.AddHs(mol)
        
        params = AllChem.ETKDGv3()
        params.randomSeed = 42
        ret = AllChem.EmbedMolecule(mol, params)
        if ret == -1:
            ret = AllChem.EmbedMolecule(mol, randomSeed=42)
        if ret == -1:
            return None
        
        AllChem.MMFFOptimizeMolecule(mol, mmffVariant='MMFF94')
        
        # 手动生成XYZ
        conf = mol.GetConformer()
        atoms = [atom.GetSymbol() for atom in mol.GetAtoms()]
        coords = [conf.GetAtomPosition(i) for i in range(mol.GetNumAtoms())]
        
        lines = [str(len(atoms)), 'Generated by DrugDesign Agent']
        for atom, coord in zip(atoms, coords):
            lines.append(f'{atom:>2}  {coord.x:12.6f}  {coord.y:12.6f}  {coord.z:12.6f}')
        
        return '\n'.join(lines)
    except Exception:
        return None


def get_molecule_structure(smiles: str, format: str = 'sdf') -> Optional[str]:
    """获取分子结构，支持sdf/pdb/xyz格式"""
    format = format.lower().strip()
    if format == 'sdf':
        return smiles_to_sdf(smiles)
    elif format == 'pdb':
        return smiles_to_pdb(smiles)
    elif format == 'xyz':
        return smiles_to_xyz(smiles)
    else:
        return smiles_to_sdf(smiles)


def get_structure_info(smiles: str) -> Dict:
    """获取分子结构信息（键长、键角等）"""
    mol = validate_smiles(smiles)
    if mol is None:
        return {}
    
    AllChem = _get_allchem()
    if AllChem is None:
        return {}
    
    try:
        mol = Chem.AddHs(mol)
        params = AllChem.ETKDGv3()
        params.randomSeed = 42
        ret = AllChem.EmbedMolecule(mol, params)
        if ret == -1:
            ret = AllChem.EmbedMolecule(mol, randomSeed=42)
        if ret == -1:
            return {}
        
        AllChem.MMFFOptimizeMolecule(mol, mmffVariant='MMFF94')
        
        conf = mol.GetConformer()
        
        # 计算基本几何信息
        num_atoms = mol.GetNumAtoms()
        num_bonds = mol.GetNumBonds()
        
        # 计算分子范围
        xs, ys, zs = [], [], []
        for i in range(num_atoms):
            pos = conf.GetAtomPosition(i)
            xs.append(pos.x)
            ys.append(pos.y)
            zs.append(pos.z)
        
        return {
            'num_atoms': num_atoms,
            'num_bonds': num_bonds,
            'num_heavy_atoms': mol.GetNumHeavyAtoms(),
            'bounds': {
                'x_min': round(min(xs), 3), 'x_max': round(max(xs), 3),
                'y_min': round(min(ys), 3), 'y_max': round(max(ys), 3),
                'z_min': round(min(zs), 3), 'z_max': round(max(zs), 3),
            },
            'center': {
                'x': round(sum(xs) / len(xs), 3),
                'y': round(sum(ys) / len(ys), 3),
                'z': round(sum(zs) / len(zs), 3),
            }
        }
    except Exception:
        return {}
